name: Run Docker Container

on:
  push:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Build Docker image
      run: docker build --progress=plain --build-arg BUILDKIT_INLINE_CACHE=1 -t wdio-v9:latest -f Dockerfile .
